### ISSUE TITLE
The meaning of the json files

### ISSUE THREAD

**Issue by sheldonl3** [alexantoniades/polar#1]
Hi,alexantoniades! I m very interested in this project. But I am not sure the meanings of these json files,like blacklist.json, and each field of the inputs.json. Could you elaborate on the principle?

**Comment by alexantoniades** [comment]
Hi sheldonl3. Yes, of course. Thank you for showing interest in the project.

"blacklist.json" holds an array of flagged words (strings), commands, arguments or sequences which you would determine as suspicious coming from a user.

I implemented this because the userbase context is different from system to system. i.e. "mpirun", "ssh" might be suspicious in one system but not in another etc. and since the pre-processor checks the complete user input command, feel free to include arguments of commands (i.e. "ssh -p 22" or "-p 22") or even complete commands (i.e. "ssh -p 22 target@some_ip").

In "inputs.json" is essentially an array of arrays and each component array can be explained in the "encode" method here: https://github.com/alexantoniades/polar/blob/master/tools.py#L131 

In essence index 0 is the mean severity weight (explained below), index 1 is either a "1" or a "0" if the user which executed the command exists in the system, keep in mind the file "/data/users.json" is supposed to exists but was removed for security reasons. Index 2 is either "1" or "0" if the input command (as string) contains a flagged (or blacklisted) word.

The approach i took in this project was calculating a float which represents severity of command depending on the weight of each word in the input command string. This means 1 is most severe and 0 is least severe, in a general sense "sudo" would be 1 and "ls" would be 0. Keep in mind this weight factor isn't limited to just commands, this would be any type of string would or would not pose any threat according to the "blacklist.json". If the word is flagged, it's automatically 1, else its weight is calculated using the number of times the command occurs in the complete -triaining- dataset (of strings). My assumption in this was that suspicious commands are generally encountered the least, hence the less you see a command being used the more suspicious it would appear.
 
Hopes this helps, let me know if you have any further questions.

**Comment by sheldonl3** [comment]
Thanks for your reply！
So this is my understanding of the project: Actually,there is an original "command file", like"[[cmd:sudo vi /user/... ,user:user1],[...]] ". So with blacklist.json and user.json , we can calculating each array in inputs.json. Like what you said above. And statisticsing the number of occurrences of keywords in commands, saving it in occurrences.json. The output.json show is each command safe or not. When training,using the input.json, output.json.
When making predictions for a new command, using blacklist.json,occurrences.json and user.json to calculate a new array like each in input.json ,entering it into the model we got.
Is my understanding correct?

**Comment by alexantoniades** [comment]
You are spot on! 

The original raw training dataset (before pre-processing) was not included for security reasons because this model was tested on actual user activity.

Essentially, the raw format is as you mentioned.
```json
[
   { "command": "sudo apt install python", "user": 1 },
   { "command": "cd /etc/NetworkManager", "user": 1 },
   { "command": "cd /home/user26/Downloads", "user": 26 },
   { "command": "ls /home/user99/Projects", "user": 99 },
]
```

First each command should be extracted to an array like: 
```json
// Filename: ./data/vocabulary.json
[ 
   "sudo apt install python", 
   "cd /etc/NetworkManager"
   "cd /home/user26/Downloads", 
   "ls /home/user99/Projects" 
]
// Then broken into:
[ 
   "sudo", 
   "apt",
   "install",
   "python",
   "cd", 
   "/etc/NetworkManager"
   "cd",
   "/home/user26/Downloads", 
   "ls", 
   "/home/user99/Projects" 
]
```
A vocabulary needs to be constructed and given to the "Occurrences" object. It's not a problem if there are multiple instances of a string, in fact it's needed.
```python
from tools import importJSON, Occurrences
# Import data from JSON files
vocabulary = importJSON("./data/vocabulary.json")
users = importJSON("./data/users.json")
blacklist = importJSON("./data/blacklist.json")

# Initialise occurrence object
o = Occurrences( vocabulary, users, blacklist )
# Test it
command, user = "sudo apt install python", "1" 
result = o.encode(command, user)
# result probably returns something like [ 0.1, 1, 1 ]

command, user = "cd /home", "26" 
result = o.encode(command, user)
# result probably returns something like [ 0.7, 1, 0 ]

command, user = "sudo apt install python", "90" 
result = o.encode(command, user)
# result probably returns something like [ 0.1, 0, 1 ]
```

This code isn't tested but should be good enough for understanding. Feel  free to ask me any further questions.

**Comment by sheldonl3** [comment]
Thanks! That help a lot!
